require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MilesController do

  # This should return the minimal set of attributes required to create a valid
  # Mile. As you add validations to Mile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "airline" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all miles as @miles" do
      mile = Mile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:miles).should eq([mile])
    end
  end

  describe "GET show" do
    it "assigns the requested mile as @mile" do
      mile = Mile.create! valid_attributes
      get :show, {:id => mile.to_param}, valid_session
      assigns(:mile).should eq(mile)
    end
  end

  describe "GET new" do
    it "assigns a new mile as @mile" do
      get :new, {}, valid_session
      assigns(:mile).should be_a_new(Mile)
    end
  end

  describe "GET edit" do
    it "assigns the requested mile as @mile" do
      mile = Mile.create! valid_attributes
      get :edit, {:id => mile.to_param}, valid_session
      assigns(:mile).should eq(mile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mile" do
        expect {
          post :create, {:mile => valid_attributes}, valid_session
        }.to change(Mile, :count).by(1)
      end

      it "assigns a newly created mile as @mile" do
        post :create, {:mile => valid_attributes}, valid_session
        assigns(:mile).should be_a(Mile)
        assigns(:mile).should be_persisted
      end

      it "redirects to the created mile" do
        post :create, {:mile => valid_attributes}, valid_session
        response.should redirect_to(Mile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mile as @mile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mile.any_instance.stub(:save).and_return(false)
        post :create, {:mile => { "airline" => "invalid value" }}, valid_session
        assigns(:mile).should be_a_new(Mile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mile.any_instance.stub(:save).and_return(false)
        post :create, {:mile => { "airline" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mile" do
        mile = Mile.create! valid_attributes
        # Assuming there are no other miles in the database, this
        # specifies that the Mile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mile.any_instance.should_receive(:update).with({ "airline" => "MyString" })
        put :update, {:id => mile.to_param, :mile => { "airline" => "MyString" }}, valid_session
      end

      it "assigns the requested mile as @mile" do
        mile = Mile.create! valid_attributes
        put :update, {:id => mile.to_param, :mile => valid_attributes}, valid_session
        assigns(:mile).should eq(mile)
      end

      it "redirects to the mile" do
        mile = Mile.create! valid_attributes
        put :update, {:id => mile.to_param, :mile => valid_attributes}, valid_session
        response.should redirect_to(mile)
      end
    end

    describe "with invalid params" do
      it "assigns the mile as @mile" do
        mile = Mile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mile.to_param, :mile => { "airline" => "invalid value" }}, valid_session
        assigns(:mile).should eq(mile)
      end

      it "re-renders the 'edit' template" do
        mile = Mile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mile.any_instance.stub(:save).and_return(false)
        put :update, {:id => mile.to_param, :mile => { "airline" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mile" do
      mile = Mile.create! valid_attributes
      expect {
        delete :destroy, {:id => mile.to_param}, valid_session
      }.to change(Mile, :count).by(-1)
    end

    it "redirects to the miles list" do
      mile = Mile.create! valid_attributes
      delete :destroy, {:id => mile.to_param}, valid_session
      response.should redirect_to(miles_url)
    end
  end

end
